kenshoo/react-multi-select

.storybook/webpack.config.js
package.json
yarn.lock

fix storybook configuration

---

.babelrc
tests/react_multi_select_utils.spec.js

@talyak @AmirAsaraf 
The following PR adds some tests to the util methods.

Add tests to util methods

---

README.md

Add demo link to readme

---

index.js

@AmirAsaraf @talyak 
The following PR adds a root index that will allow us to import our component with
```import MultiSelect from "@kenshooui/react-multi-select"```

add root index

---

.storybook/preview-head.html
src/multi_selection_list/multiselection_list.js
src/multi_selection_list/multiselection_list.scss
src/multi_selection_list/virtualized_items/multiselection_virtualized_items.js
src/multi_selection_list/virtualized_items/multiselection_virtualized_items.scss
src/react_multi_select.js
src/react_multi_select.scss
stories/multi-select.stories.js

This PR includes some fixes to scss files and some refactoring
@liorheber please check out the styling refresh issue
**Not include**
scss refactor and reorganise

Fix styling - phase 1

---

stories/custom_style.scss
stories/multi-select.stories.js

Add more storybook states

---

src/components/react_multi_select.js

fix partial select view

---

README.md
src/components/multi_selection_list/multiselection_list.js
src/components/react_multi_select.js
src/components/react_multi_select_messages.js
stories/custom_style.scss
stories/multi-select.stories.js

1) default messages
2) custom icons
3) remove errors

Default messages and custom icons

---

.npmignore
.storybook/webpack.config.js
config/webpack/webpack.common.js
package.json
src/components/multi_selection_list/virtualized_items/multiselection_virtualized_items.js
yarn.lock

@AmirAsaraf @talyak 
The following PR reduces the bundle size from 1MB to 268KB according to webpack.
I also removed some un-used dependencies and removed things that shouldn't have been in the npm module.

Cleanup project

---

src/components/multi_selection_list/multiselection_list.js
src/components/react_multi_select.js

@AmirAsaraf @talyak 
The following PR removes un-used methods from the class

Remove un-used methods

---

src/components/items/selected_item.scss

Fixes #
#61 
-Change the x icon to align properly

Align x icon when items selected

---

README.md
stories/multi-select.stories.js

Fixes #58
- Styled the custom components.
- Added documentation for missing custom renderers props

Style the customized component story

---

package.json

Fixes #67 
Added the following keywords to the package:
multiselect
form
input
listtolist
react
react-component
select
ui
multi-select

Add keywords to npm package

---

package.json
yarn.lock

Fixes #69 
Added a prettier pre commit hook based on option 1 here:
https://prettier.io/docs/en/precommit.html
@talyak @AmirAsaraf

Add prettier pre-commit hook

---

.npmignore
.travis.yml
README.md
package.json

Fixes #57 
Support test coverage with code climate

create test coverage

---

stories/custom_components/item.js
stories/custom_components/search.js
stories/custom_components/select_all.js
stories/custom_components/selected_item.js
stories/custom_components/selection_status.js
stories/multi-select.stories.js

#72 
- clean up storybook to improve repo score

Clean up storybook code

---

src/components/list/list.js
src/components/list/list.scss
src/components/multi_select_state.js
tests/components/list/list.spec.js
tests/components/multi_select_state.spec.js

Support multi selection with shift key

---

src/components/multi_select.js
stories/multi-select.stories.js
tests/components/__snapshots__/multi_select.spec.js.snap
tests/components/multi_select.spec.js

Add support for showSelectedItems - default =  true

---

src/components/destination_list.js
src/components/multi_select.js
src/components/multi_select_state.js
tests/components/__snapshots__/destination_list.spec.js.snap
tests/components/__snapshots__/multi_select.spec.js.snap
tests/components/destination_list.spec.js
tests/components/multi_select.spec.js
tests/components/multi_select_state.spec.js

Select all should conform to the filter.

---

src/components/destination_list.js
tests/components/destination_list.spec.js

fix unselect bug

---

src/components/list/items_list.js
src/components/multi_select_state.js
tests/components/list/items_list.spec.js
tests/components/multi_select_state.spec.js

https://github.com/kenshoo/react-multi-select/issues/80
https://github.com/kenshoo/react-multi-select/issues/81
Fixes #
Please see this branch: https://github.com/kenshoo/react-multi-select/tree/state_bugs to reproduce the bugs
-
-
-

Fix bugs with selected items and items state

---

package.json
src/components/items/item.js
src/components/items/item_label.js
src/components/items/item_label.scss
src/components/items/selected_item.js
tests/components/items/__snapshots__/item.spec.js.snap
tests/components/items/__snapshots__/item_label.spec.js.snap
tests/components/items/__snapshots__/selected_item.spec.js.snap
tests/components/items/item_label.spec.js
yarn.lock

Fixes #83 
The X icon in selected items is remain even if the text is too long with tooltip.

The X icon doesn't remain when the text is too long

---

README.md
src/components/list/items_list.js
src/components/list/list.js
src/components/source_list.js
stories/multi-select.stories.js
tests/components/__snapshots__/source_list.spec.js.snap
tests/components/list/items_list.spec.js
tests/components/list/list.spec.js
tests/components/source_list.spec.js

Fixes https://github.com/kenshoo/react-multi-select/issues/86
add ability to display tooltip on disabled items

add ability to display tooltip on disabled items

---

README.md

Fixes https://github.com/kenshoo/react-multi-select/issues/88
update readme - server side search example

update readme - server side search example

---

README.md
src/components/items/item.js
src/components/items/item_label.js
src/components/items/selected_item.js
src/components/multi_select.js
src/components/source_list.js
stories/multi-select.stories.js
tests/components/__snapshots__/multi_select.spec.js.snap
tests/components/__snapshots__/source_list.spec.js.snap
tests/components/multi_select.spec.js
tests/components/source_list.spec.js

Fixes #90 
Component will now accept a selectAllHeight prop that could override the itemHeight prop.
I apologize but looks like someone committed code without linting so some additional files are accidentally changed.

Support selectAllHeight prop

---

package.json
src/components/items/item.js
src/components/items/selected_item.js
src/components/loader/loader.js
src/components/search/search.js
stories/custom_components/search.js
stories/custom_components/selection_status.js
yarn.lock

Fixes #93 
- Upgrade to @materia-ui/core@1.0.0
@AmirAsaraf @talyak FYI

Upgrade to material-ui stable version

---

src/components/multi_select_state.js
tests/components/multi_select_state.spec.js

Fixes #
https://github.com/kenshoo/react-multi-select/issues/104
- Added a componentWillReceivePropsLifecycle method to handle the value changing from outside the component and filter items in response.

Added a will receive props method to filter items on every search value change

---

README.md
package.json
src/components/destination_list.js
src/components/item_grouping_util.js
src/components/items/item.js
src/components/items/item.scss
src/components/items/selected_item.js
src/components/items/selected_item.scss
src/components/list/list.js
src/components/multi_select.js
src/components/source_list.js
stories/multi-select.stories.js
stories/multi_select_stories_util.js
tests/components/__snapshots__/destination_list.spec.js.snap
tests/components/__snapshots__/multi_select.spec.js.snap
tests/components/__snapshots__/source_list.spec.js.snap
tests/components/destination_list.spec.js
tests/components/item_grouping_util.spec.js
tests/components/items/__snapshots__/item.spec.js.snap
tests/components/items/__snapshots__/selected_item.spec.js.snap
tests/components/items/item.spec.js
tests/components/items/selected_item.spec.js
tests/components/source_list.spec.js
yarn.lock

Fixes https://github.com/kenshoo/react-multi-select/issues/62
- Add item grouping feature
- Send "withGrouping" to MultiSelect component
- Add "group" prop to each item with it's group name

Item grouping

---

package.json
yarn.lock

Fixes #116
Upgrade prop-types to the latest version.

upgrade prop-types dependency to latest

---

package.json
yarn.lock

this PR fix [this alert](https://github.com/kenshoo/react-multi-select/network/alerts)

fix security vulnerability alert

---

package.json
src/components/multi_select.js
tests/components/__snapshots__/multi_select.spec.js.snap
tests/components/multi_select.spec.js
yarn.lock

add jssProvider

---

package.json
src/components/source_list.js
src/components/with_search.js
tests/components/__snapshots__/multi_select.spec.js.snap
tests/components/__snapshots__/source_list.spec.js.snap
tests/components/__snapshots__/with_search.spec.js.snap
tests/components/multi_select.spec.js
tests/components/source_list.spec.js
tests/components/with_search.spec.js
yarn.lock

Goal: to add support for search to right section
This is the first step - moving existing logic from source list to reusable HOC
Document with full explanation of what is the plan: [link](https://docs.google.com/document/d/1U-HZVtua6XniQklX-qgCDJ3-95Q5KyeEccl5d1ZzaZY/edit)

BREAKING CHANGE: Move Search logic to reusable HOC

---

package.json
src/components/with_responsive_height.js
tests/components/__snapshots__/multi_select.spec.js.snap
tests/components/multi_select.spec.js
yarn.lock

Fixes #143
- removed react-height package
- replace approach with usage react-height
- updated related snapshot

Throws warning: List doesn't get rendered when items are loaded async and select component is hidden

---

src/components/multi_select_state.js
stories/multi-select.stories.js

- Able to use the component as a controlled components

Feature : MultiSelect can be used as a controlled component (#156)

---

.storybook/config.js

- Remove 3 Storybook deprecation warnings

Remove Storybook warnings
